service: bu-page-capture

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:*Object"
      Resource: "arn:aws:s3:::${file(config.yml):S3_BUCKET_NAME}*"
  apiKeys:
    - capturePingKey
  usagePlan:
    quota: 
      limit: 1500
      period: MONTH
    throttle:
      burstLimit: 1
      rateLimit: 1

functions:
  capture:
    handler: handler.endpoint
    #maximum processing time for API Gateway invocation is 30 seconds
    timeout: 30
    environment:
        CAPTURE_URL: ${file(config.yml):CAPTURE_URL}
        S3_BUCKET_NAME: ${file(config.yml):S3_BUCKET_NAME}
        S3_PATH: ${file(config.yml):S3_PATH}
        SUBDIR_PREFIX: ${file(config.yml):SUBDIR_PREFIX}

    events:
      - http:
          path: ping
          method: get
          private: true
      - schedule:
          rate: rate(1 hour)
          enabled: false
